name: multiculturalapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^0.5.0+1
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1

  firebase_messaging: ^7.0.0

  hexcolor: ^1.0.6
  google_sign_in: ^4.5.5
  flutter_svg: ^0.17.4
  cached_network_image: ^2.2.0+1
  provider: ^4.1.3

  grouped_list: ^3.3.0
  material_design_icons_flutter: ^4.0.5345
  flutter_auth_buttons: ^0.9.0
  intl: ^0.16.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/icontest3.png"
  adaptive_icon_background: "#ffe664"
  adaptive_icon_foreground: "dev_assets/icontest3.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf


    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

    - family: Gebody
      fonts:
        - asset: assets/fonts/Gebody.ttf

    - family: Futura
      fonts:
        - asset: assets/fonts/Futura.otf

  assets:






    - assets/images/iniciallogo.png
    - assets/images/congratstrophy.png
    - assets/images/girlplayer.png
    - assets/images/goldtrophy.png
    - assets/images/silvergroup.png
    - assets/images/silverTrophy2.png
    - assets/images/sunlogin.png
    - assets/images/iconsconnect.png
    - assets/images/homeappbar.png
    - assets/images/paulatrophy.png
    - assets/images/smalllogo.png